//
// Created by 21481 on 2026/3/26.
//

#ifndef DM_H723_LIB_CHASSIS_VROUND_TASK_H
#define DM_H723_LIB_CHASSIS_VROUND_TASK_H

#define CHASSIS_TURN_ROUND 1
#define CHASSIS_NO_TURN_ROUND 0

#endif //DM_H723_LIB_CHASSIS_VROUND_TASK_H
