//
// Created by 21481 on 2026/3/10.
//

#ifndef DM_H723_LIB_UP_STAIRS_TASK_H
#define DM_H723_LIB_UP_STAIRS_TASK_H

#define UP_STAIRS_MAX_LEG_LENGTH 0.2f
#define UP_STAIRS_MIN_LEG_LENGTH MIN_VIRTUAL_LEG_LENGTH

#endif //DM_H723_LIB_UP_STAIRS_TASK_H
